name: Build Website

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:

    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install the theme
      run: |
        git clone --depth=1 --single-branch --branch mechmotum https://github.com/mechmotum/pelican-alchemy.git
    - name: Install the plugins
      run: |
        git clone --depth=1 https://github.com/getpelican/pelican-plugins.git
    - uses: nelsonjchen/gh-pages-pelican-action@0.2.0
      env:
        PELICAN_CONFIG_FILE: publishconf.py
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        GH_PAGES_CNAME: "2023.bmdconf.org"
